### ISSUE TITLE
error:  ./word2vecf/word2vecf: cannot execute binary file

### ISSUE THREAD

**Issue by PuddingCoder** [zhezhaoa/ngram2vec#8]
Hi，首先感谢贵组将开源embedding工具ngram2vec。我在用ngram2vec时出错，想请教一下。

uni-bi.sh 执行出错 ./word2vecf/word2vecf: cannot execute binary file 

Mac OS 10.13.6 

查阅资料说是 在Linux下的执行文件在MacOS上无法运行。
https://superuser.com/questions/724301/how-to-solve-bash-cannot-execute-binary-file

> According to your file output, this program is for GNU/Linux. I know this because:

> The file b1 is in the ELF (Extensible and Linkable Format) format, while Mac OS X uses the Mach-O format for binaries;

> file recognizes this file is for GNU/Linux 2.6.18, meaning it'll work on most modern Linux distributions.

> To  solve your problem, you must either run this problem within a Linux distribution, recompile the program, or get the Mac OS X version of this program.

想请问uni_bi.sh 计算SGNS的word2vecf/word2vecf是否为word2vec/makefile执行编译后生成的二进制文件呢？ 可否用macOS重新编译呢？
······································
另外，为什么demo_simplified.sh 不需要执行word2vecf二进制文件，执行word2vecf.py也可以计算SGNS，word2vecf二进制执行文件 和 word2vecf.py是什么关系呢？

**Comment by zhezhaoa** [comment]
您好 需要您make重新编译，在macos上面应该是没有问题的。我提供的可执行文件是linux的
这个工具包提供了C语言的和python语言的word2vec实现。这两个之间没有关系。python的很慢，就是一个简单的例子，实际中都用C语言的。
